In [18]:
import numpy as np
import sympy as sp

In [10]:
# vectors
v1 = np.array([[1], [0], [0]])
v2 = np.array([[0], [1], [0]])
v3 = np.array([[0], [0], [1]])

# transformed vectors
tv1 = np.array([[1], [3], [-4]])
tv2 = np.array([[2], [-1], [-3]])
tv3 = np.array([[4], [5], [-11]])

# transformation matrix T
T = np.hstack((tv1, tv2, tv3))

tv1, tv2, tv3, T

(array([[ 1],
        [ 3],
        [-4]]),
 array([[ 2],
        [-1],
        [-3]]),
 array([[  4],
        [  5],
        [-11]]),
 array([[  1,   2,   4],
        [  3,  -1,   5],
        [ -4,  -3, -11]]))

In [12]:
### Q1: find rank

T_matrix = np.array([
    [1, 2, 4],
    [3, -1, 5],
    [-4, -3, -11]
])

rank_T = np.linalg.matrix_rank(T_matrix)

rank_T

2

In [15]:
### Q3: determinant M x N

M = np.array([  
                [1, 0, 1],
                [0, 1, 0],
                [1, 1, 1]
            ])

N = np.array([
                [2, 8, 7],
                [4, 3, 9],
                [1, 9, 5]
            ])

M_times_N = M @ N

det_M_times_N = np.linalg.det(M_times_N)

print("Product of M and N:")
print(M_times_N)
print("\nDeterminant of the product matrix (det(M * N)):", det_M_times_N)


Product of M and N:
[[ 3 17 12]
 [ 4  3  9]
 [ 7 20 21]]

Determinant of the product matrix (det(M * N)): 0.0


In [17]:
### Q4:

vectors = np.array([
            [2, 1, 1], 
            [1, 0, 0], 
            [1, 2, 1]
        ])

check_span_3D = np.linalg.matrix_rank(vectors) == 3

check_span_3D, np.linalg.matrix_rank(vectors)

(True, 3)

In [3]:
### Q5: basis for the 3D space

sets_of_vectors = {
    'set1': np.array([[2, 0, -1], [3, -1, 1], [1, 2, 4]]),
    'set2': np.array([[1, 0, 1], [0, 1, 0], [1, 0, 0]]),
    'set3': np.array([[2, 0, 0], [3, 2.5, 5.5], [1, 3.5, 4.5]]),
    'set4': np.array([[-1, 1, 1], [2, 2, 0], [1, 2, 1]]),
    'set5': np.array([[-1, 1, 1], [2, 2, 6], [1, 2, 5]])
}

determinants = {}
for key, value in sets_of_vectors.items():
    det = np.linalg.det(value)
    determinants[key] = det

bases_for_3D = {}
for key, det in determinants.items():
    if np.abs(det) > 1e-10:
        bases_for_3D[key] = 'Yes'
    else:
        bases_for_3D[key] = 'No'

determinants, bases_for_3D

({'set1': -19.000000000000004,
  'set2': -1.0,
  'set3': -16.000000000000007,
  'set4': -2.0,
  'set5': 0.0},
 {'set1': 'Yes', 'set2': 'Yes', 'set3': 'Yes', 'set4': 'Yes', 'set5': 'No'})

In [20]:
### Q6: chacacteristic polynomial (dikurang mean->(lamda-lamda1)(lamda-lamda2))

matrix_M = sp.Matrix([
                        [2, 1], 
                        [-3, 6]
                    ])

lambda_symbol = sp.symbols('lambda')
char_poly = matrix_M.charpoly(lambda_symbol).as_expr()

char_poly

lambda**2 - 8*lambda + 15

In [22]:
### Q7: find covariance matrix

M = np.array([
    [3, 2],
    [5, 8]
])

# 1. centralize matrix
M_centralized = M - M.mean(axis=0)

# 2. covariance matrix (1/(n-1)) * (X^T * X)
n = M.shape[0]
covariance_matrix = (1 / (n - 1)) * M_centralized.T.dot(M_centralized)

covariance_matrix

array([[ 2.,  6.],
       [ 6., 18.]])

In [23]:
### Q8: eigenvectors of this matrix

M = np.array([
                [3, 0], 
                [-2, 1]
            ])

eigenvector_dict = {}
eigenvalues, eigenvectors = np.linalg.eig(M)

for i in range(len(eigenvalues)):
    eigenvector_dict[eigenvalues[i]] = eigenvectors[:, i]

eigenvalues, eigenvector_dict

(array([1., 3.]),
 {1.0: array([0., 1.]), 3.0: array([ 0.70710678, -0.70710678])})

In [24]:
### Q9 dan Q10: eigenvalues and covariance matrix

X = np.array([
    [70, 2, 2],
    [110, 4, 2]
])

# mean
mu = X.mean(axis=0)

# 1. centralize matrix
X_mu = X - mu

# 2. covariance matrix
n = X.shape[0]
covariance_matrix = (1 / (n - 1)) * np.dot(X_mu.T, X_mu)

# eigenvalues
eigenvalues = np.linalg.eigvals(covariance_matrix)

X_mu, eigenvalues

(array([[-20.,  -1.,   0.],
        [ 20.,   1.,   0.]]),
 array([802.,   0.,   0.]))